In [1]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\souvi\appdata\roaming\python\python314\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\souvi\appdata\roaming\python\python314\site-packages (from pandas) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\souvi\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\souvi\appdata\roaming\python\python314\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\souvi\appdata\roaming\python\python314\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\souvi\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import numpy as np
import pandas as pd

In [3]:
labels = ['a', 'b', 'c']
my_data = [10, 20, 30]
arr = np.array([10,25,50])
d = {'a':10, 'b':20, 'c':30}

In [4]:
pd.Series(my_data)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(data=my_data)
pd.Series(data=my_data, index=labels)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(arr)

0    10
1    25
2    50
dtype: int64

In [7]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [8]:
# When we combine multiple series it becomes a DataFrame

In [9]:
data = {
    'Name':['Souvik','Sourav','Suman'],
    'Age':[24,25,26],
    'City':['Kolkata','Mumbai','Chennai']
    
}

In [12]:
df = pd.DataFrame(data)
df

     Name  Age     City
0  Souvik   24  Kolkata
1  Sourav   25   Mumbai
2   Suman   26  Chennai

In [13]:
data_list = [
    [ 'Souvik', 24, 'Kolkata' ],
    [ 'Sourav', 25, 'Mumbai' ],
    [ 'Suman', 26, 'Chennai' ]
]
df2 = pd.DataFrame(data_list)

In [14]:
df2

        0   1        2
0  Souvik  24  Kolkata
1  Sourav  25   Mumbai
2   Suman  26  Chennai

In [15]:
df2 = pd.DataFrame(data_list, columns=['Name', 'Age', 'City'])
df2

     Name  Age     City
0  Souvik   24  Kolkata
1  Sourav   25   Mumbai
2   Suman   26  Chennai

In [16]:
df2['Name']

0    Souvik
1    Sourav
2     Suman
Name: Name, dtype: object

In [17]:
df2[['Name', 'City']]

     Name     City
0  Souvik  Kolkata
1  Sourav   Mumbai
2   Suman  Chennai

In [20]:
df2["Designation"] = ['AI Engineer', 'ML Engineer', 'Data Analyst']
df2

     Name  Age     City   Designation
0  Souvik   24  Kolkata   AI Engineer
1  Sourav   25   Mumbai   ML Engineer
2   Suman   26  Chennai  Data Analyst

In [23]:
df2.drop('Age',axis=1)

     Name     City   Designation
0  Souvik  Kolkata   AI Engineer
1  Sourav   Mumbai   ML Engineer
2   Suman  Chennai  Data Analyst

In [24]:
df2

     Name  Age     City   Designation
0  Souvik   24  Kolkata   AI Engineer
1  Sourav   25   Mumbai   ML Engineer
2   Suman   26  Chennai  Data Analyst

In [25]:
df2.drop('Age', axis=1, inplace=True)
df2

     Name     City   Designation
0  Souvik  Kolkata   AI Engineer
1  Sourav   Mumbai   ML Engineer
2   Suman  Chennai  Data Analyst

In [26]:
df2.loc[0]

Name                Souvik
City               Kolkata
Designation    AI Engineer
Name: 0, dtype: object

In [27]:
df2.loc[[0,1]]

     Name     City  Designation
0  Souvik  Kolkata  AI Engineer
1  Sourav   Mumbai  ML Engineer

In [28]:
df2.loc[[0]]

     Name     City  Designation
0  Souvik  Kolkata  AI Engineer

In [32]:
df2.loc[[0,1]][['Name','City']]

     Name     City
0  Souvik  Kolkata
1  Sourav   Mumbai

In [31]:
df2.loc[[1,2]][["Name"]]

     Name
1  Sourav
2   Suman

In [33]:
data2 = {
    "Name": ["Amit Sharma","Priya Verma","Rahul Mehta","Sneha Iyer","Arjun Patel",
             "Neha Singh","Rohit Kumar","Kavya Nair","Suresh Rao","Ananya Bose",
             "Vikram Joshi","Pooja Malhotra","Manish Gupta","Riya Kapoor","Karan Malhotra"],
    "Age": [28,32,45,26,38,29,41,34,50,27,36,31,44,24,39],
    "City": ["Bangalore","Delhi","Mumbai","Chennai","Ahmedabad",
             "Pune","Noida","Kochi","Hyderabad","Kolkata",
             "Jaipur","Gurgaon","Indore","Delhi","Chandigarh"],
    "Designation": ["Software Engineer","Data Analyst","Project Manager","Junior Developer",
                    "Product Manager","UI/UX Designer","Engineering Manager",
                    "Data Scientist","CTO","Business Analyst",
                    "DevOps Engineer","HR Manager","Operations Manager",
                    "Trainee Engineer","Cloud Architect"],
    "Salary": [850000,720000,1500000,550000,1350000,680000,1800000,
               1200000,3500000,600000,1100000,900000,1400000,420000,1600000]
}

In [35]:
df3 = pd.DataFrame(data2)
df3

              Name  Age        City          Designation   Salary
0      Amit Sharma   28   Bangalore    Software Engineer   850000
1      Priya Verma   32       Delhi         Data Analyst   720000
2      Rahul Mehta   45      Mumbai      Project Manager  1500000
3       Sneha Iyer   26     Chennai     Junior Developer   550000
4      Arjun Patel   38   Ahmedabad      Product Manager  1350000
5       Neha Singh   29        Pune       UI/UX Designer   680000
6      Rohit Kumar   41       Noida  Engineering Manager  1800000
7       Kavya Nair   34       Kochi       Data Scientist  1200000
8       Suresh Rao   50   Hyderabad                  CTO  3500000
9      Ananya Bose   27     Kolkata     Business Analyst   600000
10    Vikram Joshi   36      Jaipur      DevOps Engineer  1100000
11  Pooja Malhotra   31     Gurgaon           HR Manager   900000
12    Manish Gupta   44      Indore   Operations Manager  1400000
13     Riya Kapoor   24       Delhi     Trainee Engineer   420000
14  Karan Malhotra   39  Chandigarh      Cloud Architect  1600000

In [ ]:
df3[df3['Age']>30]

              Name  Age        City          Designation   Salary
1      Priya Verma   32       Delhi         Data Analyst   720000
2      Rahul Mehta   45      Mumbai      Project Manager  1500000
4      Arjun Patel   38   Ahmedabad      Product Manager  1350000
6      Rohit Kumar   41       Noida  Engineering Manager  1800000
7       Kavya Nair   34       Kochi       Data Scientist  1200000
8       Suresh Rao   50   Hyderabad                  CTO  3500000
10    Vikram Joshi   36      Jaipur      DevOps Engineer  1100000
11  Pooja Malhotra   31     Gurgaon           HR Manager   900000
12    Manish Gupta   44      Indore   Operations Manager  1400000
14  Karan Malhotra   39  Chandigarh      Cloud Architect  1600000

In [37]:
df3[(df3['Age']>30) & (df3['City']=='Mumbai')]

          Name  Age    City      Designation   Salary
2  Rahul Mehta   45  Mumbai  Project Manager  1500000

In [38]:
df3[df3['Age']>30 & df3['City']=='Mumbai']

TypeError: Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]

Your logic is fine. Your syntax is wrong. Pandas isn’t Python here—it’s NumPy boolean indexing, and you violated its rules.

The error
df3[df3['Age']>30 & df3['City']=='Mumbai']

What’s wrong (exactly)

Operator precedence
& runs before > and ==.
So Python reads it like this (which is garbage):

df3['Age'] > (30 & df3['City']) == 'Mumbai'


That makes no sense → ValueError / TypeError

Missing parentheses
Every condition in pandas boolean indexing MUST be wrapped in parentheses.

✅ Correct code
df3[(df3['Age'] > 30) & (df3['City'] == 'Mumbai')]

Rule you must remember (no excuses)

Use & not and

Use | not or

ALWAYS wrap each condition in parentheses

❌ Wrong

df3['Age'] > 30 & df3['City'] == 'Mumbai'


✅ Right

(df3['Age'] > 30) & (df3['City'] == 'Mumbai')

Bonus: common variations
# OR condition
df3[(df3['Age'] > 30) | (df3['City'] == 'Mumbai')]

# NOT condition
df3[~(df3['City'] == 'Mumbai')]

In [46]:
data4 = {
'A': [1, 2, np.nan, 4, 5],
'B': [1, 2, 3, 4, 5],
'C': [1, 2, 3, np.nan, np.nan],
'D': [1, np.nan, np.nan, np.nan, 5]
}

In [47]:
df4 = pd.DataFrame(data4)
df4

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [43]:
df4.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [48]:
df4.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [49]:
# Removing missing values
# It works on rows by default

df4.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
df4.dropna(thresh=4) # Keep rows with at least 4 non-NA values

     A  B    C    D
0  1.0  1  1.0  1.0

In [52]:
# Filling the missing values

df4.fillna(value=0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [53]:
val = {'A':0, 'B':99, 'C':-1, 'D':100}
df4.fillna(value=val)

     A  B    C      D
0  1.0  1  1.0    1.0
1  2.0  2  2.0  100.0
2  0.0  3  3.0  100.0
3  4.0  4 -1.0  100.0
4  5.0  5 -1.0    5.0

In [55]:
employees = pd.DataFrame({
'employee_id': [1, 2, 3, 4, 5],
'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})
# DataFrame 2: Salary information
salaries = pd.DataFrame({
'employee_id': [1, 2, 3, 6, 7],
'salary': [60000, 80000, 65000, 70000, 90000],
'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [56]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [57]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [58]:
pd.merge(employees,salaries)

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [ ]:
pd.merge(employees, salaries, on='employee_id', how='outer')
# Meaning of on --> The on parameter specifies the common column(s) to join on. In this case, both DataFrames have an employee_id column, so we use that as the key for merging.
# Meaning of how --> The how parameter determines the type of merge to be performed. An outer join includes all records from both DataFrames, filling in NaN for missing matches.

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [ ]:
pd.merge(employees, salaries, on='employee_id', how='left')
# left means all records from the left DataFrame (employees) and matching records from the right DataFrame (salaries). If there is no match, NaN values are filled in for the right DataFrame's columns.

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [61]:
pd.merge(employees, salaries, on='employee_id', how='right')
# right means all records from the right DataFrame (salaries) and matching records from the left DataFrame (employees). If there is no match, NaN values are filled in for the left DataFrame's columns.

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [65]:
df10 = pd.DataFrame({
'A': ['AB', 'A1', 'A2'],
'B': ['Be', 'B1', 'B2'],
'C': ['ce', 'C1', 'C2']
})
df20 = pd.DataFrame({
'A': ['A3', 'A4', 'A5'],
'B': ['B3', 'B4', 'B5'],
'C': ['C3', 'C4', 'C5']
})

In [66]:
df10

    A   B   C
0  AB  Be  ce
1  A1  B1  C1
2  A2  B2  C2

In [67]:
df20

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [68]:
pd.concat([df10, df20])

    A   B   C
0  AB  Be  ce
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [70]:
pd.concat([df10, df20], axis=1)

    A   B   C   A   B   C
0  AB  Be  ce  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [71]:
df11 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df12 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [72]:
df11

      name
1    Alice
2      Bob
3  Charlie

In [73]:
df12

   score
2     85
3     90
4     75

In [74]:
df11.join(df12,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [75]:
df12.join(df11)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

In [77]:
data6 = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df6 = pd.DataFrame(data6)

In [78]:
df6

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [79]:
# Group by Store and calculate the sum of sales
cat = df6.groupby('Store')['Sales'].sum()

In [80]:
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [85]:
# Group by Category and calculate the sum of sales

cat1 = df6.groupby('Category')['Sales'].sum()

In [86]:
cat1

Category
A    570
B    930
Name: Sales, dtype: int64

In [87]:
# Group by multiple columns
# Group by Category and Store
cat2 = df.groupby(['Category','Store'])['Sales'].sum()
cat2

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [88]:
# Aggregation

df6['Sales'].mean()

np.float64(187.5)

In [90]:
df6['Sales'].agg(['sum','mean','max','min','count','std','median'])

sum       1500.000000
mean       187.500000
max        300.000000
min        100.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

In [91]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    909     34   John  January      Q1
1  2023-01-02       B   West    979     90   Mary  January      Q1
2  2023-01-03       C  North    591     53    Bob  January      Q1
3  2023-01-04       D  South    394     58  Alice  January      Q1
4  2023-01-05       A   East    428     34   John  January      Q1
5  2023-01-06       B   West    723     26   Mary  January      Q1
6  2023-01-07       C  North    664     60    Bob  January      Q1
7  2023-01-08       D  South    773     53  Alice  January      Q1
8  2023-01-09       A   East    163     10   John  January      Q1
9  2023-01-10       B   West    670     56   Mary  January      Q1
10 2023-01-11       C  North    464     60    Bob  January      Q1
11 2023-01-12       D  South    799     22  Alice  January      Q1
12 2023-01-13       A   East    218     58   John  January      Q1
13 2023-01-14       B   West    671     60   Mary  January      Q1
14 2023-01-15       C  North    814     69    Bob  January      Q1
15 2023-01-16       D  South    690     69  Alice  January      Q1
16 2023-01-17       A   East    604     91   John  January      Q1
17 2023-01-18       B   West    926     40   Mary  January      Q1
18 2023-01-19       C  North    570     33    Bob  January      Q1
19 2023-01-20       D  South    778     85  Alice  January      Q1

In [92]:
pd.pivot_table(df,values = "Sales",index = 'Region',columns="Product",aggfunc = 'median')

Product      A      B      C      D
Region
East     428.0    NaN    NaN    NaN
North      NaN    NaN  591.0    NaN
South      NaN    NaN    NaN  773.0
West       NaN  723.0    NaN    NaN

In [93]:
pivot2 = pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     464.4    NaN    NaN    NaN  45.4   NaN   NaN   NaN
North      NaN    NaN  620.6    NaN   NaN   NaN  55.0   NaN
South      NaN    NaN    NaN  686.8   NaN   NaN   NaN  57.4
West       NaN  793.8    NaN    NaN   NaN  54.4   NaN   NaN

In [94]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [95]:

dff = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [96]:
dff

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [97]:
dff.shape

(5, 3)

In [98]:
dff.columns

Index(['A', 'B', 'C'], dtype='object')

In [99]:
dff.info

<bound method DataFrame.info of    A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500>

In [100]:
dff.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [101]:
dff['A'] + 5

0     6
1     7
2     8
3     9
4    10
Name: A, dtype: int64

In [102]:
dff

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [103]:
dff['D'] = dff['B'].apply(lambda x : x**3)

In [104]:
dff

   A   B    C       D
0  1  10  100    1000
1  2  20  200    8000
2  3  30  300   27000
3  4  40  400   64000
4  5  50  500  125000